source 'https://rubygems.org'

gem 'jekyll'

gem 'minima'
gem 'kramdown-parser-gfm'
gem 'github-pages'

group :jekyll_plugins do
  gem 'minima'
  gem 'jekyll-theme-cayman'
  gem 'jekyll-asciidoc'
  gem 'jekyll-coffeescript'
  gem 'jekyll-default-layout'
  gem 'jekyll-gist'
  gem 'jekyll-github-metadata'
  gem 'jekyll-paginate'
  gem 'jekyll-readme-index'
  gem 'jekyll-relative-links'
  gem 'jekyll-titles-from-headings'
  gem 'jekyll-feed'
  gem 'jekyll-seo-tag'
  gem 'jekyll-theme-slate'
  gem 'jekyll-last-modified-at'
  gem 'jekyll-toc'
  gem 'jekyll-sitemap'
  gem 'jekyll-optional-front-matter'
end

# Asciidoctor uses pygments for source highlighting
gem 'pygments.rb'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
# Performance-booster for watching directories on Windows
gem 'wdm', '~> 0.1.0' if Gem.win_platform?

# I don't know why we need these
gem 'rexml'
gem 'webrick'
